import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading='Okky Maheswara' hello='Hello, My name is' message='HAHAHA' />
      home
      <Footer />
    </>
  )
}
