import CTA from '@/components/CTA'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Project from '@/components/Project'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home &mdash; Mahesora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero hai='Hello, My name is' heading='Okky Maheswara' message='Developers' />
      <Project />
      <CTA />
      <Footer />
    </>
  )
}
